version: '3'

services:

  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54321:5432"
    networks:
      - backend
    restart: always

  fluency-strikers-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend
    restart: always

  minio:
    image: minio/minio:latest
    command: server /data
    restart: always
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - ./mnt/minio-data:/dat
    networks:
      - backend

networks:
  backend:
