import {
  REDIRECTION_ERROR_STATUS_CODES,
  CLIENT_ERROR_STATUS_CODES,
  SERVER_ERROR_STATUS_CODES,
  NO_CONTENT_ERROR_STATUS_CODES
} from './http-error-status-codes';

export {
  REDIRECTION_ERROR_STATUS_CODES,
  CLIENT_ERROR_STATUS_CODES,
  SERVER_ERROR_STATUS_CODES,
  NO_CONTENT_ERROR_STATUS_CODES
};
